### ISSUE TITLE
[Bug]: 0.4.48 not work

### ISSUE THREAD

**Issue by rainstorms** [sboesen/remotely-sync#132]
### What happened?

0.4.48 Lack  main.js

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using?

webdav

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Aha, that makes so much more sense now. Thank you for pointing this out. We'll have to wait for @sboesen.

**Comment by sboesen** [comment]
Sorry about that, added.

**Comment by Haibara-z** [comment]
I have this problem, too

**Comment by sboesen** [comment]
This issue should be resolved, can you clarify what problem you are seeing?

**Comment by hidakafinzelz** [comment]
same to me.
Tell me preparing, bug never sync

**Comment by kadisonm** [comment]
Hi @hidakafinzelz, is this still happening? 

If so, could you please press `Ctrl + Shift + I` in Obsidian and checking for any errors related to Remotely Sync. If the errors don't contain anything private (like your file names) please send a screenshot. 

Thank you!

**Comment by hidakafinzelz** [comment]
> Hi @hidakafinzelz, is this still happening?
> 
> If so, could you please press `Ctrl + Shift + I` in Obsidian and checking for any errors related to Remotely Sync. If the errors don't contain anything private (like your file names) please send a screenshot.
> 
> Thank you!

Still Happens.

Console Pannel 
![image](https://github.com/sboesen/remotely-sync/assets/131435470/71b7c711-42f5-48bf-bdbc-a6f4793c0396)


It says wrong password, but when i check in the setting pannel, It can connected

![image](https://github.com/sboesen/remotely-sync/assets/131435470/92501911-2f0b-4cbf-b0ff-57ee5797565c)

**Comment by kadisonm** [comment]
It looks like this is because the encryption password doesn't match. Make sure they're the same on both devices and press confirm. 

If it still doesn't work it might be that your remote files were encrypted with a completely different password than is set on your devices. In that case you should delete the files on the remote and try syncing them back again with the right password. (make a back up first)

**Comment by hidakafinzelz** [comment]
> It looks like this is because the encryption password doesn't match. Make sure they're the same on both devices and press confirm.
> 
> If it still doesn't work it might be that your remote files were encrypted with a completely different password than is set on your devices. In that case you should delete the files on the remote and try syncing them back again with the right password. (make a back up first)

Successfully solved. Thank you.

**Comment by kadisonm** [comment]
No worries!
