### ISSUE TITLE
[Bug]:  Toolbar sync status

### ISSUE THREAD

**Issue by FlameInBrains** [sboesen/remotely-sync#134]
### What happened?

The status stopped to show the actual state on one of the two computers that used this plugin. It shows the status: 'synced one week ago', but at the same time, synchronization works normally. The protocol that was used: WebDAV. What steps were taken: 
1) reset sync metadata(did not help)
2) Full resynchronization of data(did not help)
At the same time, the second computer shows correct sync data.

### What OS are you using?

Windows

### What remote cloud services are you using?

webdav

### Version of the plugin

0.4.48

### Version of Obsidian

1.5.12

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment]
Yeh, I think I know why this is happening. I'll see if I can fix it.

**Comment by kadisonm** [comment]
This should be fixed in 0.4.49 when #135 is merged. Please try syncing again to fix it.

Thanks for reporting the issue! :)

**Comment by FlameInBrains** [comment]
Thank you for your answer! However, I have tried to perform full resyncronization of the obsidian vault. The data was uploaded to the cloud server. The sync status now is 'Never synced'. The plugin tries to resync the whole vault data. Despite of that the notes were not redacted. At the same time, the note that was redacted is in the end of the queue and after the whole day it is still not reached. The data on the remote WebDav storage was manually erased before the resyncronization. The local plugin was reinstalled, but the syncronization still does not work correctly.

'It is just for the information, maybe it will be usefull'

**Comment by kadisonm** [comment]
That's odd, is there any errors in the console related to Remotely Sync if you press `Ctrl + Shift + I` in Obsidian?

Otherwise, it might be the issue solved above, but we'll have to wait until the PR is merged and the new version released to see if it fixes it.

**Comment by kadisonm** [comment]
@FlameInBrains please let me know if this still occurs.
